# Generated by Django 4.0.1 on 2022-01-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='identificationuser',
            name='last_name',
        ),
    ]
