# Generated by Django 4.0.1 on 2022-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_identificationuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
