# Generated by Django 4.0.1 on 2022-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_identificationuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationuser',
            name='full_name',
            field=models.CharField(default='', max_length=150, verbose_name='повне імя'),
        ),
    ]
