# Generated by Django 4.0.1 on 2022-01-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_full_name_identificationuser_namess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationuser',
            name='namess',
        ),
    ]
